query {
  repository(owner: "Thewessen", name: "CTF") {
    object(expression: "master:OverTheWire/bandit") {
      ... on Tree {
        entries {
          name
          object {
            ... on Blob {
              text
            }
          }
        }
      }
    }
  }
}
