query Languages {
  repository(owner: "Thewessen", name: "hello-world") {
    object(expression: "master:Exercism") {
      ... on Tree {
        entries {
          name
          type
        }
      }
    }
  }
}
