query {
  repository(owner: "Thewessen", name: "CTF") {
    object(expression: "master:OverTheWire") {
      ... on Tree {
        entries {
          type
          name
        }
      }
    }
  }
}
